name: Deploy to EC2

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # New Testing Step
      - name: Install dependencies and run tests
        run: |
          npm install
          npm test
        env:
          CI: true # Ensures that certain frameworks (like React) run tests in CI mode

      # Deploy to Production
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: admin
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd /var/www/brianward.tech/html
            git pull origin main
            sudo systemctl reload nginx
          EOF

      # Deploy to Staging
      - name: Deploy to Staging
        if: github.ref == 'refs/heads/development'
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: admin
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd /var/www/staging.brianward.tech/html
            git pull origin development
            sudo systemctl reload nginx
          EOF
